//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapEditor2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapEditor2.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        ///
        ///Version 2012 (Build {1}).
        ///
        ///This product has been created by Nahuel Rodrigo Ianni @ {2}  based on Microsoft XNA framework.
        ///
        ///For more info visit the site: {3}.
        /// </summary>
        internal static string AboutMapEditorContent {
            get {
                return ResourceManager.GetString("AboutMapEditorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Map Editor.
        /// </summary>
        internal static string AboutMapEditorCustomWindowTitle {
            get {
                return ResourceManager.GetString("AboutMapEditorCustomWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://create.msdn.com/en-US/.
        /// </summary>
        internal static string AboutMapEditorWebsites {
            get {
                return ResourceManager.GetString("AboutMapEditorWebsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add layer.
        /// </summary>
        internal static string AddLayerCustomWindowTitle {
            get {
                return ResourceManager.GetString("AddLayerCustomWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        internal static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to delete all tiles from the current layer.
        ///
        ///Do you wish to continue?.
        /// </summary>
        internal static string CleanCurrentLayerMsgBoxText {
            get {
                return ResourceManager.GetString("CleanCurrentLayerMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to delete all tiles from the selected layer.
        ///
        ///Do you wish to continue?.
        /// </summary>
        internal static string CleanLayerMsgBoxText {
            get {
                return ResourceManager.GetString("CleanLayerMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to delete all tiles from the map.
        ///
        ///Do you wish to continue?.
        /// </summary>
        internal static string CleanMapMsgBoxText {
            get {
                return ResourceManager.GetString("CleanMapMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTRUCTION: EMPTY CODE VALUES COMBO ITEMS..
        /// </summary>
        internal static string ClearComboKey {
            get {
                return ResourceManager.GetString("ClearComboKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear layer.
        /// </summary>
        internal static string ClearLayerCustomWindowTitle {
            get {
                return ResourceManager.GetString("ClearLayerCustomWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT Files|*.txt.
        /// </summary>
        internal static string CodeValueFileFilter {
            get {
                return ResourceManager.GetString("CodeValueFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy layer.
        /// </summary>
        internal static string CopyLayerCustomWindowTitle {
            get {
                return ResourceManager.GetString("CopyLayerCustomWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to copy all tiles within two layers. This may cause the lose of selected tiles for a layer.
        ///Do you wish to continue?.
        /// </summary>
        internal static string CopyLayerMsgBoxText {
            get {
                return ResourceManager.GetString("CopyLayerMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimelessReality.
        /// </summary>
        internal static string DesignerName {
            get {
                return ResourceManager.GetString("DesignerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy.
        /// </summary>
        internal static string Enemy {
            get {
                return ResourceManager.GetString("Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy Block.
        /// </summary>
        internal static string EnemyBlocking {
            get {
                return ResourceManager.GetString("EnemyBlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while reading the file..
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file is not a valid image..
        /// </summary>
        internal static string ErrorTileSheet {
            get {
                return ResourceManager.GetString("ErrorTileSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill layer.
        /// </summary>
        internal static string FillLayerCustomWindowTitle {
            get {
                return ResourceManager.GetString("FillLayerCustomWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to fill all tiles for the selected layer with the selected tile.
        ///
        ///Do you wish to continue?.
        /// </summary>
        internal static string FillLayerMsgBoxText {
            get {
                return ResourceManager.GetString("FillLayerMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide layer.
        /// </summary>
        internal static string HideLayerCustomWindowTitle {
            get {
                return ResourceManager.GetString("HideLayerCustomWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer {0}.
        /// </summary>
        internal static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lethal.
        /// </summary>
        internal static string Lethal {
            get {
                return ResourceManager.GetString("Lethal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Code Values.
        /// </summary>
        internal static string LoadCodeValueFile {
            get {
                return ResourceManager.GetString("LoadCodeValueFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Map.
        /// </summary>
        internal static string LoadMap {
            get {
                return ResourceManager.GetString("LoadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to change the tile sheet source file. 
        ///Consider that this can change the images inside the layers.
        ///
        ///If you continue with the change, don&apos;t forget to change the size of the tiles on the map configuration accordingly to the new size of the tiles in the tile sheet.
        ///
        ///Do you wish to continue?.
        /// </summary>
        internal static string LoadNewTileSheetMsgBoxText {
            get {
                return ResourceManager.GetString("LoadNewTileSheetMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Tile Sheet.
        /// </summary>
        internal static string LoadTileSheet {
            get {
                return ResourceManager.GetString("LoadTileSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify map gravity.
        /// </summary>
        internal static string ModifyMapGravityCustomWindowTitle {
            get {
                return ResourceManager.GetString("ModifyMapGravityCustomWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Map.
        /// </summary>
        internal static string NewMapCustomWindowTitle {
            get {
                return ResourceManager.GetString("NewMapCustomWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before attempting to fill an entire layer you must select a tile from the list..
        /// </summary>
        internal static string NoTileSelected {
            get {
                return ResourceManager.GetString("NoTileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current map has pending changes that are about to be lost.
        ///
        ///Do you wish to continue?.
        /// </summary>
        internal static string PendingChanges {
            get {
                return ResourceManager.GetString("PendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redimension map size.
        /// </summary>
        internal static string RedimensionMapSizeCustomWindowTitle {
            get {
                return ResourceManager.GetString("RedimensionMapSizeCustomWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to change the size of the map.
        ///This can cause the unintended lose of information.
        ///
        ///Do you wish to continue?.
        /// </summary>
        internal static string RedimensionMapSizeMsgBoxText {
            get {
                return ResourceManager.GetString("RedimensionMapSizeMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redimension tile size.
        /// </summary>
        internal static string RedimensionTileSizeCustomWindowTitle {
            get {
                return ResourceManager.GetString("RedimensionTileSizeCustomWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option should only be used when dealing with tile sheets where tiles have a size different than {0} x {1}.
        ///
        ///Do you wish to continue?.
        /// </summary>
        internal static string RedimensionTileSizeMsgBoxText {
            get {
                return ResourceManager.GetString("RedimensionTileSizeMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to delete all tiles from the current layer.
        ///
        ///Do you wish to continue?.
        /// </summary>
        internal static string RemoveCurrentLayerMsgBoxText {
            get {
                return ResourceManager.GetString("RemoveCurrentLayerMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove layer.
        /// </summary>
        internal static string RemoveLayerCustomWindowTitle {
            get {
                return ResourceManager.GetString("RemoveLayerCustomWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to delete all tiles from the selected layer.
        ///
        ///Do you wish to continue?.
        /// </summary>
        internal static string RemoveLayerMsgBoxText {
            get {
                return ResourceManager.GetString("RemoveLayerMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Map.
        /// </summary>
        internal static string SaveMap {
            get {
                return ResourceManager.GetString("SaveMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP0000.
        /// </summary>
        internal static string SimpleMapName {
            get {
                return ResourceManager.GetString("SimpleMapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Files|*.png|JPG Files|*.jpg|Bitmap Files|*.bmp.
        /// </summary>
        internal static string TileSheetFileFilter {
            get {
                return ResourceManager.GetString("TileSheetFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load file..
        /// </summary>
        internal static string UnableToLoadFile {
            get {
                return ResourceManager.GetString("UnableToLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown map.
        /// </summary>
        internal static string UnknownMap {
            get {
                return ResourceManager.GetString("UnknownMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files|*.XML.
        /// </summary>
        internal static string XmlFileFilter {
            get {
                return ResourceManager.GetString("XmlFileFilter", resourceCulture);
            }
        }
    }
}
